name: Auto Fetch Gold Price

on:
  schedule:
    # Chạy tự động cứ mỗi 30 phút
    - cron: '*/10 * * * *'
  workflow_dispatch: # Cho phép chạy thủ công bất cứ lúc nào

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python fetch_gold.py